services:
  chyrplite:
    build: .
    container_name: chyrp-lite-default
    restart: always
    volumes:
      - data:/data
      - uploads:/var/www/html/uploads
    networks:
      - cloudflared
      - chyrp_internal
    deploy:
      resources:
        limits:
          cpus: '0.5'

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - chyrp_internal

volumes:
  data:
  uploads:
  dbdata:
networks:
  cloudflared:
    external: true
  chyrp_internal:
